### ISSUE TITLE
How to use it as unified/mdast module? 

### ISSUE THREAD

**Issue by hugmanrique** [leonardodino/gatsby-remark-figure-caption#1]
Hi! I've been looking for a plugin like this for weeks, and it was amazing to discover yours yesterday! I placed it under the remark plugins array on a MDX.js config (`mdPlugins`) with no options as so:

```js
require('@zeit/next-mdx')({
  options: {
    mdPlugins: [require('gatsby-remark-figure-caption')]
  }
});
```

And tried rendering a big Markdown file (I can share it, but it's too long and it will be painful to diagnose where the issue is exactly; you can find a rendered HTML copy [here](https://hugmanrique.me/blog/deploying-playpen-with-gitlab-ci)) and got the following error:

```
Module build failed (from ./node_modules/@mdx-js/loader/index.js):
TypeError: Cannot read property 'children' of undefined
    at one (D:\<PROJECT_ROOT>\node_modules\unist-util-visit-parents\index.js:36:14)
    at visitParents (D:\<PROJECT_ROOT>\node_modules\unist-util-visit-parents\index.js:22:3)
    at visit (D:\<PROJECT_ROOT>\node_modules\unist-util-visit\index.js:22:3)
    at Function.module.exports (D:\<PROJECT_ROOT>\node_modules\gatsby-remark-figure-caption\index.js:13:3)
    at freeze (D:\<PROJECT_ROOT>\node_modules\unified\index.js:123:28)
    at Function.process (D:\<PROJECT_ROOT>\node_modules\unified\index.js:360:5)
    at compile (D:\<PROJECT_ROOT>\node_modules\@mdx-js\mdx\index.js:125:39)
    at Object.module.exports (D:\<PROJECT_ROOT>\node_modules\@mdx-js\loader\index.js:10:20)
 @ multi ./pages/posts/deploying-playpen-with-gitlab-ci.mdx
```

I hope you can find where the issue is without having to analyze the provided Markdown file. I tried searching for the issue, but didn't find anything (I'm a bit of a remark newbie 😅). Feel free to take your time to fix this, I don't strictly need it right now. Thanks for your awesome work!

**Comment by leonardodino** [comment]
Hello there, @hugmanrique 

it seems like `@zeit/next-mdx`'s `mdPlugins` are handled via `unified` plugins, which have a different function syntax.

can you try something along these lines: 

```javascript
const figureCaptionTransfomer = require('gatsby-remark-figure-caption');

require('@zeit/next-mdx')({
  options: {
    mdPlugins: [() => figureCaptionTransfomer}]
  }
});
```

**PS**: i just skimmed the docs, maybe I'm missing something else.

this plugin was made to work with `gatsby`.
it has a different semantics, but fortunately it manipulates `MDAST`, so it may be possible.

**Comment by leonardodino** [comment]
any updates @hugmanrique?

without an isolated test case i cannot help much :/

**Comment by hugmanrique** [comment]
It's not working with your provided method, will publish a test repo soon.

**Comment by hugmanrique** [comment]
I've setup a repo which contains a repro test on https://github.com/hugmanrique/gatsby-remark-figure-caption-next-mdx-error-repro (all the steps are detailed on the `README.md` file)

**Comment by leonardodino** [comment]
@hugmanrique 
`mdPlugins: [() => markdownAST => figureCaptionTransfomer({markdownAST})]`

ping me if it works (:

update: tried locally, it does on the reproduction repo.

**Comment by hugmanrique** [comment]
Yup, it works flawlessly now! Thanks for the quick response and this great project 😊
