### ISSUE TITLE
Plugin producing illegal HTML output

### ISSUE THREAD

**Issue by hugmanrique** [leonardodino/gatsby-remark-figure-caption#3]
I'm sorry for being so annoying, but when I compile the following Markdown document with this plugin it's producing illegal HTML (and React is complaining about it, check facebook/react#6295 for the same error):

```md
Content above

![The weekly Unsplash photo](https://source.unsplash.com/weekly/)

Content below
```

produces

```html
<p>Content above</p>
<p><figure><img src="https://source.unsplash.com/weekly/"><figcaption>The weekly Unsplash photo</figcaption></figure></p>
<p>Content below</p>
```

According to the MDN docs, the `<p>` element only accepts phrasing content which `<figure>` is not part of. https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content

**Comment by leonardodino** [comment]
that's actually not done this plugin, it's how markdown works.
everything is in paragraphs by default. this plugins converts only the image.

although it might a good thing, to add some transformation to it's parent, it will always depend on the intended output, and there are several "correct" ways. 
eg: changing the `p` element to a `div`, unwrapping it to the root, etc.
but each and every one of those can disturb the content if the figure is surrounded by text in the same element.

**conclusion**: i think it's better handled through another transformer, so it can split paragraphs around and stuff. 

---

in `gatsby-land` we have [this](https://github.com/Hebilicious/gatsby-remark-component), that converts `<p>` to `<div>`.
(spoiler: it won't work with this plugin, only with raw `html` tags)

but something similar to it can solve the illegal output.
I suggest diving into `AST` transformation, is easier than it seems.
the code for the figure transformation is a bit too abstract, and not a good place to learn, but there are many wonderful ones.

---

one way of handling is parsing the generated HTML AST, [check if the node is not phrasing content](https://www.npmjs.com/package/hast-util-phrasing) and replace its parent with a `div`

**Comment by leonardodino** [comment]
a quick hack like this might work:

```javascript
const visit = require('unist-util-visit')

const fixCaptionPlugin = () => tree => visit(
	tree,
	'element',
	(node, index, parent) => {
		if(node.tagName !== 'figure') return
		parent.tagName = 'div'
	},
)

require('@zeit/next-mdx')({
  options: {
	mdPlugins: [() => markdownAST => figureCaptionTransfomer({markdownAST})],
	hastPlugins: [fixCaptionPlugin],
  },
})
```

**Comment by hugmanrique** [comment]
Thank you, that seemed to do the job! As you said, this plugin is primarily directed towards Gatsby users and I understand why adding something like this would be hard to maintain/could break some things.
